### PR TITLE
Replace NSMutableSet with NSHashTable when Appropriate #trivial

### LINKED ISSUE #312: [ASCollection] Exception on suspend, [NSSet addObject:nil]
This is on Texture as of ~1 week ago, roughly 2.3.2.

Immediately upon app suspend, just to re-run the app, there was a crash because an elementmap was queried for a layout attribute and returned nil. There is no nil check before attempting to inset into a set.

cc @nguyenhuy @Adlai-Holler as I think this code is relatively new and so this is likely a real issue.

```
(lldb) po [map elementForLayoutAttributes:la]
 nil
2017-05-28 14:29:26.386[16211:3656362] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSSetM addObject:]: object cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000111bc4b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000111630141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000111b19e3f -[__NSSetM addObject:] + 783
	3   TestApp                             0x0000000104df5f9c -[ASCollectionViewLayoutController elementsWithinRangeBounds:map:] + 1260
	4   TestApp                             0x0000000104df4ebf -[ASCollectionViewLayoutController elementsForScrolling:rangeMode:rangeType:map:] + 303
	5   TestApp                             0x0000000104e1d002 -[ASRangeController _updateVisibleNodeIndexPaths] + 2834
	6   TestApp                             0x0000000104e1beb5 -[ASRangeController updateIfNeeded] + 85
	7   TestApp                             0x0000000104e21309 +[ASRangeController didEnterBackground:] + 1065
	8   CoreFoundation                      0x0000000111b63c2c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	9   CoreFoundation                      0x0000000111b63b29 _CFXRegistrationPost + 425
	10  CoreFoundation                      0x0000000111b63892 ___CFXNotificationPost_block_invoke + 50
	11  CoreFoundation                      0x0000000111b27162 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	12  CoreFoundation                      0x0000000111b262c1 _CFXNotificationPost + 673
	13  Foundation                          0x00000001097f0b24 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	14  UIKit                               0x0000000109d4ca6a __47-[UIApplication _applicationDidEnterBackground]_block_invoke + 117
	15  UIKit                               0x0000000109ef6f4c +[UIViewController _performWithoutDeferringTransitions:] + 114
	16  UIKit                               0x0000000109d4c9a3 -[UIApplication _applicationDidEnterBackground] + 110
	17  UIKit                               0x0000000109d4cec0 -[UIApplication _handleApplicationDeactivationWithScene:shouldForceExit:transitionContext:completion:] + 709
	18  UIKit                               0x0000000109d60786 -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] + 461
	19  UIKit                               0x0000000109d42921 __70-[UIApplication scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 159
	20  UIKit                               0x0000000109d42599 -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] + 978
	21  UIKit                               0x000000010a260d9c -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 509
	22  FrontBoardServices                  0x0000000112b57f81 __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.376 + 205
	23  FrontBoardServices                  0x0000000112b855f6 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	24  FrontBoardServices                  0x0000000112b8546d -[FBSSerialQueue _performNext] + 186
	25  FrontBoardServices                  0x0000000112b857f6 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	26  CoreFoundation                      0x0000000111b6ac01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	27  CoreFoundation                      0x0000000111b500cf __CFRunLoopDoSources0 + 527
	28  CoreFoundation                      0x0000000111b4f5ff __CFRunLoopRun + 911
	29  CoreFoundation                      0x0000000111b4f016 CFRunLoopRunSpecific + 406
	30  GraphicsServices                    0x0000000112ff7a24 GSEventRunModal + 62
	31  UIKit                               0x0000000109d450d4 UIApplicationMain + 159
	32  TestApp                             0x00000001036dd1d5 main + 197
	33  libdyld.dylib                       0x000000011259865d start + 1
)

```
screen shot 2017-05-28 at 2 29 05 pm

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Resolves #312 and improves performance by replacing `-hash` and `-isEqual:` with pointer work.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: Source/Layout/ASLayoutSpec.mm [hunk 1]
```diff
@@ -170,11 +170,12 @@ - (ASTraitCollection *)asyncTraitCollection
 
 #pragma mark - Framework Private
 
-- (nullable NSSet<id<ASLayoutElement>> *)findDuplicatedElementsInSubtree
+#if DEBUG
```
Comment (garrettmoon) [inline Source/Layout/ASLayoutSpec.mm]: Should this be `AS_DEDUPE_LAYOUT_SPEC_TREE`?

File: Source/Private/Layout/ASLayoutSpecPrivate.h [hunk 2]
```diff
@@ -27,10 +27,12 @@ NS_ASSUME_NONNULL_BEGIN
   NSMutableArray *_childrenArray;
 }
 
+#if DEBUG
```
Comment (garrettmoon) [inline Source/Private/Layout/ASLayoutSpecPrivate.h]: Here too?
