### PR TITLE
[ASDataController] Add event logging for transaction queue flush duration #trivial

### LINKED ISSUE #333: [ASDataController / Developement Ease] Add event logging for transaction queue flush duration
One of the most common performance problems in a Texture app occurs when a developer makes multiple edit transactions to a collection / table right after each other, before the processing of the previous operation is finished. In this case, Texture blocks on the completion of the current edit operation, even though it would have been asynchronous if the second / subsequent operation had not been started. 

The `ASEventLog` provides the ability to capture the information on this subtle perf issue. In the `-ASDataController updateWithChangeSet:` method, we can time the duration of the dispatch group wait of the editing transaction queue and log both the time as well as the stack trace so the developer can see which edit operations are triggering performance issues.

### PR DESCRIPTION
**Pull request by hannahmbanana**
One of the most common performance problems in a Texture app occurs when a developer makes multiple edit transactions to a collection / table right after each other, before the processing of the previous operation is finished. In this case, Texture blocks on the completion of the current edit operation, even though it would have been asynchronous if the second / subsequent operation had not been started.

The ASEventLog provides the ability to capture the information on this subtle perf issue. In the -ASDataController updateWithChangeSet: method, we can time the duration of the dispatch group wait of the editing transaction queue and log both the time as well as the stack trace so the developer can see which edit operations are triggering performance issues.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: Source/Details/ASDataController.mm [hunk 1]
```diff
@@ -485,7 +486,11 @@ - (void)updateWithChangeSet:(_ASHierarchyChangeSet *)changeSet
     _initialReloadDataHasBeenCalled = YES;
   }
   
-  dispatch_group_wait(_editingTransactionGroup, DISPATCH_TIME_FOREVER);
+  NSTimeInterval transactionQueueFlushDuration;
```
Comment (appleguy) [inline Source/Details/ASDataController.mm]: Add an initialization, = 0.0f;  This would be initialized to 0 automatically if an instance variable, but in this case it's technically needed.

File: Source/Details/ASDataController.mm [hunk 2]
```diff
@@ -498,7 +503,7 @@ - (void)updateWithChangeSet:(_ASHierarchyChangeSet *)changeSet
   [self invalidateDataSourceItemCounts];
   
   // Log events
-  ASDataControllerLogEvent(self, @"triggeredUpdate: %@", changeSet);
+  ASDataControllerLogEvent(self, @"triggeredUpdate (waited on editing queue for %@ms): %@", transactionQueueFlushDuration * 1000, changeSet);
```
Comment (appleguy) [inline Source/Details/ASDataController.mm]: Change %@ms to %fms

**Comment by hannahmbanana** [comment]
@appleguy: The event log shows fractions of a ms, while the console log timestamp shows ~100+ms. Any ideas?

**Comment by hannahmbanana** [comment]
@nguyenhuy - FYI, this logging may be incorrect - I suspect it's understating the number of ms. @appleguy - did you have a chance to take a look at some test values?
