### PR TITLE
Fix double-load issue with ASCollectionNode

### LINKED ISSUE #351: [ASCollectionNode] Node may load data twice during initial load.
I haven't narrowed the conditions down exactly, but I was building tests for some new collection node API and I noticed this issue. We get `numberOfSections, numberOfItemsInSection, nodeBlockForItem` twice for the entire data set on initial load.

I'll attach the unit test when I put up the PR in a minute. @nguyenhuy or I should look into this when there's time.

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Resolves #351 
- Make `[ASCollectionView reloadData*]` unavailable, not deprecated. This is breaking API but the methods have been deprecated for going on 7 months.
  - We can't reliably tell the difference between clients calling this method, and UICollectionView itself calling this method, so we can't safely override it and change its behavior.
  - We now unconditionally forward this call to super. 
  - It's OK for clients to blindly call `reloadData` on a view that has been cast to `(UICollectionView *)` but it just won't do what they expect. Nothing will actually change.
- Modify `[ASCollectionNode reloadData*]` to do the real work.
- Update unit tests.

### CODE REVIEW

File: Source/ASCollectionNode.mm [hunk 1]
```diff
@@ -682,24 +683,34 @@ - (void)waitUntilAllUpdatesAreCommitted
...
+  ASDisplayNodeAssertMainThread();
+  [self reloadData];
+  [self waitUntilAllUpdatesAreCommitted];
 }
 
-- (void)reloadDataImmediately
+- (void)relayoutItems
 {
-  [self.view reloadDataImmediately];
+  [self.view relayoutItems];
```
Comment (Adlai-Holler) [inline Source/ASCollectionNode.mm]: I swapped the order of these two methods to group the `reloadData*` methods together.

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please ensure license is correct for ASCollectionViewTests.mm:</p>
<pre><code>//
//  ASCollectionViewTests.mm
//  Texture
//
//  Copyright (c) 2014-present, Facebook, Inc.  All rights reserved.
//  This source code is licensed under the BSD-style license found in the
//  LICENSE file in the /ASDK-Licenses directory of this source tree. An additional
//  grant of patent rights can be found in the PATENTS file in the same directory.
//
//  Modifications to this file made after 4/13/2017 are: Copyright (c) 2017-present,
//  Pinterest, Inc.  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
</code></</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: Source/ASCollectionNode.mm [hunk 2]
```diff
@@ -682,24 +683,34 @@ - (void)waitUntilAllUpdatesAreCommitted
...
+  if (!self.nodeLoaded) {
+    return;
   }
+  
+  [self performBatchUpdates:^{
+    [self.view.changeSet reloadData];
+  } completion:^(BOOL finished){
+    if (completion) {
+      completion();
+    }
```
Comment (Adlai-Holler) [inline Source/ASCollectionNode.mm]: Implementation copied from `ASCollectionView`.

File: Source/ASCollectionNode.mm (hunk 1 above)
Comment (nguyenhuy) [inline Source/ASCollectionNode.mm]: I know the original code doesn't assert main thread and check if this node is loaded, should we do these now?

File: Tests/ASCollectionViewTests.mm [hunk 3]
```diff
@@ -752,7 +754,8 @@ - (void)testThatSectionContextsAreCorrectAfterReloadData
   updateValidationTestPrologue
   
   del.sectionGeneration++;
-  [cv reloadDataImmediately];
+  [cn reloadData];
+  [cn waitUntilAllUpdatesAreCommitted];
```
Comment (nguyenhuy) [inline Tests/ASCollectionViewTests.mm]: And here.

File: Tests/ASCollectionViewTests.mm [hunk 4]
```diff
@@ -390,12 +391,13 @@ - (void)testThatCollectionNodeConformsToExpectedProtocols
...
   __unused ASCollectionView *cv = testController.collectionView;\
-  __unused ASCollectionNode *cn = testController.collectionNode;\
+  ASCollectionNode *cn = testController.collectionNode;\
   UIWindow *window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];\
   [window makeKeyAndVisible]; \
   window.rootViewController = testController;\
   \
-  [testController.collectionView reloadDataImmediately];\
+  [cn reloadData];\
+  [cn waitUntilAllUpdatesAreCommitted]; \
```
Comment (nguyenhuy) [inline Tests/ASCollectionViewTests.mm]: Same here, `[cn reloadDataImmediately]`?

File: Tests/ASCollectionViewTests.mm [hunk 5]
```diff
@@ -259,7 +259,8 @@ - (void)testSelection
   [window setRootViewController:testController];
   [window makeKeyAndVisible];
   
-  [testController.collectionView reloadDataImmediately];
+  [testController.collectionNode reloadData];
+  [testController.collectionNode waitUntilAllUpdatesAreCommitted];
```
Comment (nguyenhuy) [inline Tests/ASCollectionViewTests.mm]: Shouldn't we call `reloadDataImmediately` directly?

Comment (Adlai-Holler) [inline Tests/ASCollectionViewTests.mm]: No because it's deprecated.

File: Tests/ASCollectionViewTests.mm (hunk 4 above)
Comment (Adlai-Holler) [inline Tests/ASCollectionViewTests.mm]: No because it's deprecated.

File: Tests/ASCollectionViewTests.mm (hunk 3 above)
Comment (Adlai-Holler) [inline Tests/ASCollectionViewTests.mm]: No because it's deprecated.

File: Tests/ASCollectionViewTests.mm (hunk 4 above)
Comment (nguyenhuy) [inline Tests/ASCollectionViewTests.mm]: Got it 👍
